// app/guide/[id]/page.tsx
import GuideView from './GuideView'
import type { Guide } from '@/types/guide'

const MOCK_GUIDE: Guide = {
  id: '1',
  title: "Electromagnetism — Maxwell's Equations",
  mode: 'math-cs',
  createdAt: 'Apr 5, 2026',
  sections: [
    {
      id: 's1',
      heading: 'Introduction',
      elements: [
        { id: 'e1', type: 'paragraph', content: "Maxwell's equations are a set of four partial differential equations that form the foundation of classical electromagnetism, classical optics, and electric circuits." },
        { id: 'e2', type: 'paragraph', content: "They describe how electric and magnetic fields are generated by charges, currents, and changes of the fields." },
      ],
    },
    {
      id: 's2',
      heading: 'The Four Equations',
      elements: [
        { id: 'e3', type: 'heading', level: 3, content: "Gauss's Law for Electricity" },
        { id: 'e4', type: 'formula', content: '\\nabla \\cdot \\mathbf{E} = \\frac{\\rho}{\\epsilon_0}' },
        { id: 'e5', type: 'paragraph', content: 'The electric flux through any closed surface is proportional to the enclosed electric charge.' },
        { id: 'e6', type: 'heading', level: 3, content: "Faraday's Law" },
        { id: 'e7', type: 'formula', content: '\\nabla \\times \\mathbf{E} = -\\frac{\\partial \\mathbf{B}}{\\partial t}' },
        { id: 'e8', type: 'paragraph', content: 'A changing magnetic field induces an electric field.' },
      ],
    },
    {
      id: 's3',
      heading: 'Python Example',
      elements: [
        { id: 'e9', type: 'code', language: 'python', content: `import numpy as np

def electric_flux(E_field, area, normal):
    """Compute electric flux: Φ = E · A"""
    return np.dot(E_field, normal) * area

E = np.array([1.0, 0.0, 0.0])   # V/m
A = 2.0                           # m²
n = np.array([1.0, 0.0, 0.0])   # unit normal
print(f"Flux = {electric_flux(E, A, n)} V·m")` },
      ],
    },
  ],
}

export default async function GuidePage(props: PageProps<'/guide/[id]'>) {
  const { id } = await props.params
  // In production: fetch guide from DB using id
  const guide = { ...MOCK_GUIDE, id }

  return <GuideView guide={guide} />
}
